name: testing tagging
on:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa
          - demo
env:
  APP_VERSION: 1.0.0
jobs:
  envtest:
    name: Testing env
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.ref }}
          echo ${{ env.APP_VERSION }}
          echo ${{ github.event.release.tag_name }}
          echo ${GITHUB_REF#refs/tags/}
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.action }} 
      - name: validate app version
        run: |
          if [ $(git tag -l "${{ env.APP_VERSION }}") ]; then 
            echo "Version ${{ env.APP_VERSION }} already released. Please update your version"
            exit 1
          fi
      - name: derive version tag
        run: |
          if  [[ ${{ github.ref }} == refs/tags/ ]] ;
          then
            echo running for a release
            echo "VERSION_TAG=${{ env.APP_VERSION }}" >> $GITHUB_ENV
          else
            echo running for a ci commit
            echo "VERSION_TAG=${{ env.APP_VERSION }}-${{ github.run_number }}" >> $GITHUB_ENV
          fi
      - name: echo TAG
        run: echo ${{ env.VERSION_TAG}}

