name: testing env
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - qa
          - demo
env:
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev'}}
  ENVIRONMENT_DNS: ${{ env.ENVIRONMENT == 'demo' && 'lite.mybahmni.in' || format('{0}.{1}', env.ENVIRONMENT, 'lite.mybahmni.in') }}

jobs:
  envtest:
    name: Testing env
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      - name: step1
        run: echo ${{ env.ENVIRONMENT_DNS }}
